version: '3.8'

services:
  app:
    build: ./
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env
    environment:
      PORT: 3000
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}"
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app-network:
volumes:
  db-data:
