name: FIAP Tech Challenge Server Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build Docker Image
        run: docker build -t fiap-tech-challenge-server:latest .

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 074161922676.dkr.ecr.us-west-2.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2

      - name: Push Docker Image to ECR
        run: |
          docker tag fiap-tech-challenge-server:latest 074161922676.dkr.ecr.us-west-2.amazonaws.com/fiap-tech-challenge-server:latest
          docker push 074161922676.dkr.ecr.us-west-2.amazonaws.com/fiap-tech-challenge-server:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
